Repository FandomJingyu/Fandom-K, pull requests merged in 2025-04, with the labels that each got.

#2 chore: 프로젝트 초기 세팅 및 패키지 관리자 설정 추가
  .biomerc.json
  .gitattributes
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  vite.config.js
Labels: setup

#4 docs: README.md 초안 작성
  README.md
Labels: 📚 문서 수정

#6 Chore: GitHub Actions 설정 추가
  .github/workflows/ci.yml
Labels: 🔧 설정/빌드

#8 Chore: 깃모지, 커밋린트 설정 추가 및 디렉토리 세팅
  .husky/pre-commit
  commitlint.config.js
  index.html
  package-lock.json
  package.json
  public/mocks/mock01.png
  public/mocks/mock02.png
  public/mocks/mock03.png
  public/mocks/mock04.png
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/TestComponents.jsx
  src/index.css
  src/main.jsx
  src/mocks/donations.js
  src/mocks/idols.js
  src/pages/Landing/index.jsx
  src/pages/List/index.jsx
  src/pages/Mypage/index.jsx
  src/styles/commonStyles.jsx
  src/styles/layoutStyles.jsx
  src/styles/resetStyles.jsx
Labels: setup

#12 🔧 Docs: 이슈 템플릿에 마일스톤 및 할 일 리스트 추가
  .github/ISSUE_TEMPLATE/new-issue.yaml
Labels: 🔧 설정/빌드, 🚨 우선순위

#16 🔧 Chore: husky와 biome 설정 추가
  .husky/pre-commit
  package.json
Labels: ⚡ 핫픽스, 🔧 설정/빌드, 🚨 우선순위

#20 ✨ Feat: 헤더와 푸터에 Emotion 스타일 적용
  public/icons/github-mark-white.svg
  src/App.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/layouts/DefaultLayout.jsx
Labels: ✨ 기능개발, 🎨 UI 개선

#21 ✨ Feat: 공통 RadioButton 컴포넌트 구현
  public/images/radio-false.svg
  public/images/radio-true.svg
  src/components/RadioButton/index.jsx
Labels: ✨ 기능개발

#23 🎨 Feat:"아이돌 공통컴포넌트작업"
  package-lock.json
  package.json
  public/images/Karina.jpeg
  src/App.jsx
  src/components/Circle.jsx
  src/components/ProfileXIcon.jsx
  src/pages/Mypage/index.jsx
Labels: ✨ 기능개발, 🎨 UI 개선

#24 Feature/landing
  index.html
  package-lock.json
  package.json
  public/images/favicon/android-chrome-192x192.png
  public/images/favicon/android-chrome-512x512.png
  public/images/favicon/apple-touch-icon.png
  public/images/favicon/favicon-16x16.png
  public/images/favicon/favicon-32x32.png
  public/images/favicon/favicon.ico
  public/images/favicon/manifest.json
  public/images/landing/blur01.png
  public/images/landing/blur02.png
  public/images/landing/landing_card01.png
  public/images/landing/landing_card02.png
  public/images/landing/landing_card03.png
  public/images/landing/landing_card04.png
  public/images/landing/landing_card05.png
  public/images/landing/landing_card06.png
  public/images/landing/landing_card07.png
  public/images/landing/landing_card08.png
  public/images/landing/landing_fade01.png
  public/images/landing/landing_fade02.png
  public/images/landing/landing_fade03.png
  public/images/landing/landing_icon01.png
  public/images/landing/landing_icon02.png
  public/images/landing/landing_icon03.png
  public/images/landing/landing_mock01.png
  public/images/landing/landing_mock02.png
  public/images/landing/landing_mock03.png
  public/images/landing/logo.svg
  public/images/landing/logo_big.png
  public/images/landing/logo_f.svg
  public/images/landing/top_btn.png
  src/App.jsx
  src/components/Circle.jsx
  src/components/ProfileXIcon.jsx
  src/pages/Landing/components/LandingBottomSection.jsx
  src/pages/Landing/components/LandingFooter.jsx
  src/pages/Landing/components/LandingHeader.jsx
  src/pages/Landing/components/LandingMiddleSection.jsx
  src/pages/Landing/components/LandingTopSection.jsx
  src/pages/Landing/index.jsx
  src/pages/Mypage/index.jsx
  src/utils/infiniteCarousel.js
Labels: ✨ 기능개발

#25 💄 Feat: Modal 컴포넌트 구현 및 스타일 분리
  public/images/btn-modal-close.png
  src/App.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.styles.jsx
  src/pages/Testpage/Testpage.jsx
Labels: ✨ 기능개발, 💄 디자인

#27 Fix/bio appjsx format
  .vscode/settings.json
Labels: ⚡ 핫픽스, 🔧 설정/빌드

#31 Feat: Button 컴포넌트 구현
  package-lock.json
  public/images/Chart.png
  public/images/credit.png
  public/images/plus_24px.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.styles.js
  src/pages/Testpage/Testpage.jsx
Labels: ✨ 기능개발

#33 Feature/credit charge component
  public/icons/icon_credit.svg
  src/components/creditCharge.jsx
  src/pages/List/index.jsx
Labels: ✨ 기능개발

#36 🔨 Footer 레이아웃 구조를 mainGrid 클래스 기반으로 리팩토링
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.styles.js
  src/components/Footer/index.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.styles.js
  src/components/Header/index.jsx
  src/components/Modal/index.jsx
  src/layouts/DefaultLayout.jsx
  src/pages/Testpage/Testpage.jsx
Labels: 💄 디자인, 🔨 리팩토링, 🎨 UI 개선

#40 ✨ Feat: API 통합 구조 설계 및 공통 모듈 분리
  package-lock.json
  package.json
  src/apis/axios.js
  src/apis/donationsAPI.js
  src/apis/idolsAPI.js
  src/pages/Testpage/Testpage.jsx
Labels: ✨ 기능개발, ⚡ 핫픽스

#42 ♻️ Refactor: RadioButton 컴포넌트 시맨틱태그 적용
  src/components/RadioButton/index.jsx
  src/pages/Testpage/Testpage.jsx
Labels: 🔨 리팩토링

#45 Feature/mypage UI
  src/mocks/idols.js
  src/pages/Mypage/Mypage.styles.js
  src/pages/Mypage/components/IdolList/IdolList.styles.js
  src/pages/Mypage/components/IdolList/index.jsx
  src/pages/Mypage/index.jsx
Labels: 💄 디자인, 🎨 UI 개선

#46 ✨ Feat: 크레딧 상태 관리를 위한 CreditContext 및 Provider 구현
  src/App.jsx
  src/context/CreditContext.jsx
  src/pages/Testpage/index.jsx
Labels: ✨ 기능개발

#51 Refactor/modal portal
  package-lock.json
  src/components/Modal/Modal.styles.js
  src/components/Modal/Modal.styles.jsx
  src/components/Modal/ModalPortal.jsx
  src/components/Modal/Portal.jsx
  src/components/Modal/index.jsx
  src/components/Modal/modalPortalManager.js
  src/pages/Testpage/index.jsx
Labels: ✨ 기능개발, 🔨 리팩토링, 🎨 UI 개선

#52 🎨 Refactor: 후원을 기다리는 조공(Donation) 컴포넌트 UI 개선
  src/pages/List/Donation/Donation.style.js
  src/pages/List/Donation/components/Card/Card.style.js
  src/pages/List/Donation/index.jsx
  src/pages/List/index.jsx
  src/pages/Testpage/Testpage.jsx
Labels: 🎨 UI 개선

#55 ✨ 이달의 차트 완성, 기능작업
  package-lock.json
  package.json
  src/components/Circle.jsx
  src/pages/List/Chart/Chart.styles.js
  src/pages/List/Chart/index.jsx
  src/pages/List/Donation/components/creditCharge.jsx
  src/pages/List/index.jsx
Labels: ✨ 기능개발, 🎨 UI 개선

#57 Feature/credit recharge modal
  src/components/Button/Button.jsx
  src/components/Modal/Modal.styles.js
  src/pages/List/Donation/components/CreditRechargeModalContent.jsx
  src/pages/List/Donation/components/creditCharge.jsx
  src/pages/List/index.jsx
  src/pages/List/styles/CreditRechargeModalContent.styles.js
Labels: ✨ 기능개발, 💄 디자인

#59 🚑️ Fix: 충돌 오류 해결
  src/pages/List/Charge/components/CreditCharge.jsx
  src/pages/List/Charge/components/CreditRechargeModalContent.jsx
  src/pages/List/Charge/styles/CreditRechargeModalContent.styles.js
  src/pages/List/index.jsx
Labels: ⚡ 핫픽스

#60 ✨ Feat: 후원을 기다리는 조공(Donation) 컴포넌트 Card 컴포넌트 PorgressaBar구현
  src/context/CreditContext.jsx
  src/pages/List/Donation/components/Card/Card.style.js
  src/pages/List/Donation/components/Card/ProgressBar/ProgressBar.style.js
  src/pages/List/Donation/components/Card/ProgressBar/index.jsx
  src/pages/List/Donation/components/Card/index.jsx
  src/pages/List/Donation/components/ProgressBar/index.jsx
Labels: ✨ 기능개발

#63 Refactor/mypage UI
  package-lock.json
  package.json
  src/pages/Mypage/Mypage.styles.js
  src/pages/Mypage/components/IdolList/IdolList.styles.js
  src/pages/Mypage/components/IdolList/index.jsx
  src/pages/Mypage/index.jsx
  src/pages/Mypage/slider/slick-theme.css
  src/pages/Mypage/slider/slick.css
Labels: 🎨 UI 개선

#65 Feature/landing responsive
  .vscode/settings.json
  package-lock.json
  src/App.jsx
  src/pages/Landing/components/LandingBottomSection.jsx
  src/pages/Landing/components/LandingFooter.jsx
  src/pages/Landing/components/LandingHeader.jsx
  src/pages/Landing/components/LandingMiddleSection.jsx
  src/pages/Landing/components/LandingTopSection.jsx
  src/pages/Landing/index.jsx
  src/pages/Testpage/index.jsx
  src/styles/commonStyles.jsx
  src/styles/resetStyles.jsx
Labels: 🎨 UI 개선

#62 🚑 Fix: 슬라이더 화살표 버튼 위치 정렬 문제 수정
  src/pages/List/Donation/Donation.style.js
  src/pages/List/Donation/index.jsx
Labels: ⚡ 핫픽스, 🎨 UI 개선

#70 Fix/landing UI
  src/pages/Landing/components/LandingMiddleSection.jsx
  src/styles/commonStyles.jsx
  src/styles/layoutStyles.jsx
Labels: ⚡ 핫픽스, 🎨 UI 개선

#71 ✨ 차트 투표하기 기능추가
  src/components/Circle.jsx
  src/pages/List/Chart/index.jsx
  src/pages/List/index.jsx
Labels: ✨ 기능개발

#74 ✨ Feat: 후원을 기다리는 조공 (Donation) 컴포넌트 캐러셀 구현
  src/apis/donationsAPI.js
  src/pages/List/Donation/Donation.style.js
  src/pages/List/Donation/components/Card/ProgressBar/ProgressBar.style.js
  src/pages/List/Donation/components/Card/index.jsx
  src/pages/List/Donation/components/Carousel/Carousel.style.js
  src/pages/List/Donation/components/Carousel/index.jsx
  src/pages/List/Donation/index.jsx
Labels: ✨ 기능개발

#79 Feature/vote modal
  .vscode/settings.json
  src/apis/voteApi.js
  src/components/Modal/index.jsx
  src/pages/List/Chart/Chart.styles.js
  src/pages/List/Chart/components/ChartVoteModal.jsx
  src/pages/List/Chart/components/VoteButton.jsx
  src/pages/List/Chart/components/VoteButton.styles.js
  src/pages/List/Chart/components/VoteIdolList.jsx
  src/pages/List/Chart/components/VoteIdolList.styles.js
  src/pages/List/Chart/index.jsx
Labels: ✨ 기능개발, 💄 디자인

#82 Refactor/chart style
  src/components/Circle.jsx
  src/pages/List/Chart/Chart.styles.js
  src/pages/List/Chart/IdolProfileModal.jsx
Labels: 🎨 UI 개선

#83 Feature/mypage add idol
  public/icons/Checkmark.png
  src/components/CheckIdol.jsx
  src/pages/Mypage/Mypage.styles.js
  src/pages/Mypage/components/IdolList/IdolList.styles.js
  src/pages/Mypage/components/IdolList/index.jsx
  src/pages/Mypage/index.jsx
Labels: ✨ 기능개발

#88 Feature/vote-modal-idol-select
  src/components/CheckIdol.jsx
  src/pages/List/Chart/components/VoteIdolList.jsx
  src/pages/List/Chart/components/VoteIdolList.styles.js
Labels: ✨ 기능개발, 💄 디자인, 🎨 UI 개선

#92 ♻️ Chart 반응형 스타일 적용 (모바일/태블릿 대응)
  src/pages/List/Chart/Chart.styles.js
  src/pages/List/Chart/index.jsx
Labels: 🔨 리팩토링, 🎨 UI 개선

#94 ✨ Feat: Error 컴포넌트 구현
  src/components/Error/Error.style.js
  src/components/Error/index.jsx
  src/pages/List/Donation/Donation.style.js
  src/pages/List/Donation/index.jsx
Labels: ✨ 기능개발, 🔨 리팩토링

#95 Feature/donation detail UI
  src/App.jsx
  src/pages/DonationDetail/components/DonationDetailInfo.jsx
  src/pages/DonationDetail/components/DonationDetailText.jsx
  src/pages/DonationDetail/index.jsx
  src/pages/List/Donation/components/Card/index.jsx
Labels: ✨ 기능개발

#110 ♻️ Refactor: useDonations 훅 생성 및 로컬스토리지 기반 캐싱 추가
  src/apis/donationsAPI.js
  src/hooks/useDonation.jsx
  src/pages/List/Donation/index.jsx
Labels: 🔨 리팩토링

#108 Fix/landing responsive fix
  src/pages/Landing/components/LandingBottomSection.jsx
  src/pages/Landing/components/LandingFooter.jsx
  src/pages/Landing/components/LandingHeader.jsx
  src/pages/Landing/components/LandingMiddleSection.jsx
  src/pages/Landing/components/LandingTopSection.jsx
  src/styles/commonStyles.jsx
  src/styles/layoutStyles.jsx
Labels: 🎨 UI 개선

#111 Feature/credit charge responsive
  public/images/landing/blur01.png
  src/pages/List/Charge/components/CreditCharge.jsx
  src/pages/List/index.jsx
Labels: 🎨 UI 개선

#112 Feature/vote modal mobile responsive
  package.json
  public/icons/icon-arrow-left.svg
  src/components/CheckIdol.jsx
  src/components/Circle.jsx
  src/components/Modal/Modal.styles.js
  src/components/Modal/index.jsx
  src/components/RadioButton/index.jsx
  src/hooks/useIsMobile.js
  src/pages/List/Chart/IdolProfileModal.jsx
  src/pages/List/Chart/components/ChartVoteModal.jsx
  src/pages/List/Chart/components/VoteButton.jsx
  src/pages/List/Chart/components/VoteButton.styles.js
  src/pages/List/Chart/components/VoteIdolList.jsx
  src/pages/List/Chart/components/VoteIdolList.styles.js
  src/pages/List/Chart/index.jsx
Labels: ✨ 기능개발, 💄 디자인, 🎨 UI 개선

#114 🚑️ Fix: API 호출 에러 발생시 자동 재시도 로직 구현
  src/apis/axios.js
  src/apis/donationsAPI.js
Labels: 🔨 리팩토링, ⚡ 핫픽스

#119 Feature/mypage mobile2
  package-lock.json
  src/pages/Mypage/Mypage.styles.js
  src/pages/Mypage/components/IdolList/IdolList.styles.js
  src/pages/Mypage/components/IdolList/index.jsx
  src/pages/Mypage/hooks/useWindowSize.js
  src/pages/Mypage/index.jsx
Labels: ✨ 기능개발, 🔨 리팩토링

#125 Feature/toastify message
  .vscode/settings.json
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/Toastify.jsx
  src/pages/Testpage/index.jsx
  src/styles/resetStyles.jsx
Labels: ✨ 기능개발, 🎨 UI 개선

#128 Fix/Update chart UI
  .vscode/settings.json
  package-lock.json
  src/components/Circle.jsx
Labels: 🎨 UI 개선

#130 ✨ Feat: Donation 컴포넌트 스켈레톤UI를 구현했습니다.
  src/hooks/useDonation.jsx
  src/pages/List/Donation/components/Card/index.jsx
  src/pages/List/Donation/components/Skeleton/index.jsx
  src/pages/List/Donation/components/Skeleton/style/CardSkeleton.style.js
  src/pages/List/Donation/components/Skeleton/style/Skeleton.style.js
  src/pages/List/Donation/index.jsx
  src/styles/skeletonAnimation.jsx
Labels: ✨ 기능개발, 🎨 UI 개선

#135 Fix/credit charge animation fix
  index.html
  src/pages/List/Charge/components/CreditCharge.jsx
Labels: ⚡ 핫픽스

#137 Refactor/chart vote improvement
  package-lock.json
  package.json
  src/components/RadioButton/index.jsx
  src/hooks/useChart.jsx
  src/hooks/useChartVoteModal.jsx
  src/hooks/useIsMobile.jsx
  src/pages/List/Chart/components/ChartVoteModal.jsx
  src/pages/List/Chart/components/ChartVoteModal/Skeleton/VoteIdolSkeleton.styles.js
  src/pages/List/Chart/components/ChartVoteModal/Skeleton/index.jsx
  src/pages/List/Chart/components/ChartVoteModal/VoteButton.jsx
  src/pages/List/Chart/components/ChartVoteModal/VoteButton.styles.js
  src/pages/List/Chart/components/ChartVoteModal/VoteIdolList.jsx
  src/pages/List/Chart/components/ChartVoteModal/VoteIdolList.styles.js
  src/pages/List/Chart/components/ChartVoteModal/index.jsx
  src/pages/List/Chart/index.jsx
  src/pages/List/Donation/components/Skeleton/style/CardSkeleton.style.js
Labels: ✨ 기능개발, 🎨 UI 개선, 📈 성능 최적화

#140 ✨ Feat: 경로 별칭(@) 설정으로 import 경로 개선
  vite.config.js
Labels: 🔧 설정/빌드

#141 Refactor/credit recharge improvement
  src/pages/List/Charge/components/CreditCharge.jsx
  src/pages/List/Charge/components/CreditRechargeModalContent.jsx
  src/pages/List/Charge/styles/CreditRechargeModalContent.styles.js
Labels: 💄 디자인, 🎨 UI 개선

#142 ♻️ Refactor: Donation 컴포넌트 리팩토링
  package-lock.json
  src/apis/donationsAPI.js
  src/components/Button/Button.styles.js
  src/hooks/useDonation.jsx
  src/pages/List/Donation/components/Card/Card.style.js
Labels: 🔨 리팩토링

#143 Style/modify header background
  public/images/profile.jpg
  src/components/Header/Header.styles.js
  src/components/Header/index.jsx
Labels: 💄 디자인, 🎨 UI 개선

#147 Refactor/prevent multiple clicks
  .vscode/settings.json
  src/hooks/useChartVoteModal.jsx
  src/hooks/useSafeSubmit.jsx
  src/pages/DonationDetail/components/DonationDetailInfo.jsx
  src/pages/DonationDetail/index.jsx
  src/pages/List/Charge/components/CreditCharge.jsx
  src/pages/List/Charge/components/CreditRechargeModalContent.jsx
  src/pages/List/Chart/components/ChartVoteModal/Skeleton/index.jsx
  src/pages/List/Chart/components/ChartVoteModal/VoteButton.jsx
  src/pages/List/Chart/components/ChartVoteModal/VoteIdolList.jsx
  src/pages/List/Chart/components/ChartVoteModal/index.jsx
  src/pages/List/Chart/components/hooks/useChart.jsx
  src/pages/List/Chart/components/hooks/useChartVoteModal.jsx
  src/pages/List/Chart/index.jsx
Labels: ✨ 기능개발, 🎨 UI 개선, 📈 성능 최적화

#148 ⚡️ Fix: 전 머지된 건에 누락된 수정사항 다시 push 합니다
  src/pages/DonationDetail/components/DonationDetailInfo.jsx
Labels: ⚡ 핫픽스

#149 Feature/mypage skeleton
  src/components/CheckIdol.jsx
  src/pages/Mypage/Mypage.styles.js
  src/pages/Mypage/SkeletonSlider/index.jsx
  src/pages/Mypage/components/IdolList/IdolList.styles.js
  src/pages/Mypage/components/IdolList/index.jsx
  src/pages/Mypage/index.jsx
Labels: ✨ 기능개발, 🐛 버그 수정

#151 Feature/pre deploy cicd
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  build.sh
Labels: 📚 문서 수정, 🔧 설정/빌드

#153 Feature/pre deploy cicd
  .github/workflows/ci-cd.yml
Labels: 🔧 설정/빌드, 🚀 배포

#155 Refactor/credit charge animation
  .vscode/settings.json
  src/pages/DonationDetail/components/DonationDetailInfo.jsx
  src/pages/DonationDetail/components/DonationDetailText.jsx
  src/pages/DonationDetail/index.jsx
  src/pages/List/Charge/components/CreditCharge.jsx
  src/pages/List/index.jsx
  src/utils/postPosition.js
Labels: 🔨 리팩토링

#161 🚑️ Fix: Vercel 404 오류로 NotFound 페이지가 표시 되지 않는 문제 수정
  vercel.json
Labels: ⚡ 핫픽스, 🚀 배포

#162 Refactor/all smooth scroll
  .vscode/settings.json
  src/App.jsx
  src/components/Modal/index.jsx
  src/pages/Landing/components/LandingBottomSection.jsx
  src/pages/Landing/components/LandingMiddleSection.jsx
  src/pages/Landing/index.jsx
Labels: 🔨 리팩토링

#168 Fix/mypage image
  src/components/CheckIdol.jsx
  src/pages/Mypage/SkeletonSlider/index.jsx
  src/pages/Mypage/index.jsx
Labels: 🐛 버그 수정, 🎨 UI 개선

#169 Feature/fix chart UI
  src/pages/List/Chart/index.jsx
Labels: ✨ 기능개발, 🎨 UI 개선

#171 Feature/meta tag img
  index.html
  public/images/og-landing.png
  public/images/profile-default.png
  public/jingyu/jingyu_profile.jpg
  src/components/Header/index.jsx
Labels: 💄 디자인, 🎨 UI 개선

#174 ✨ 이달의 차트 수정
  src/hooks/useChart.js
  src/pages/List/Chart/index.jsx
Labels: ✨ 기능개발, 🎨 UI 개선

#176 Refactor/donation detail gender fix
  src/pages/DonationDetail/components/DonationDetailInfo.jsx
  src/pages/DonationDetail/components/DonationDetailText.jsx
Labels: ⚡ 핫픽스, 🎨 UI 개선

#179 ♻️ Refactor: Donation 컴포넌트 style 파일 코드 오류 개선 및 불필요한 파일 삭제
  public/jingyu/jingyu01.jpg
  public/mocks/mock01.png
  public/mocks/mock02.png
  public/mocks/mock03.png
  public/mocks/mock04.png
  src/App.jsx
  src/components/Error/Error.styles.js
  src/components/Error/index.jsx
  src/components/RadioButton/index.jsx
  src/components/TestComponents.jsx
  src/mocks/donations.js
  src/mocks/idols.js
  src/pages/List/Donation/Donation.styles.js
  src/pages/List/Donation/components/Card/Card.styles.js
  src/pages/List/Donation/components/Card/ProgressBar/ProgressBar.styles.js
  src/pages/List/Donation/components/Card/ProgressBar/index.jsx
  src/pages/List/Donation/components/Card/index.jsx
  src/pages/List/Donation/components/Carousel/Carousel.styles.js
  src/pages/List/Donation/components/Carousel/index.jsx
  src/pages/List/Donation/components/Skeleton/index.jsx
  src/pages/List/Donation/components/Skeleton/style/CardSkeleton.styles.js
  src/pages/List/Donation/components/Skeleton/style/Skeleton.styles.js
  src/pages/List/Donation/index.jsx
  src/pages/NotFound/NotFound.style.js
  src/pages/NotFound/NotFound.styles.js
  src/pages/NotFound/index.jsx
  src/pages/Testpage/index.jsx
Labels: 🔨 리팩토링

#180 ✨ Update: README.md
  .biomerc.json
  README.md
  commitlint.config.js
  package.json
  src/main.jsx
Labels: 📚 문서 수정

#182 ✨ 에러메세지
  public/images/FANDOM.png
  public/images/SM.png
  src/pages/List/Chart/index.jsx
Labels: ✨ 기능개발, 🎨 UI 개선

#185 v1.0.2
  .biomerc.json
  README.md
  commitlint.config.js
  package.json
  public/images/FANDOM.png
  public/images/SM.png
  public/jingyu/jingyu01.jpg
  public/mocks/mock01.png
  public/mocks/mock02.png
  public/mocks/mock03.png
  public/mocks/mock04.png
  src/App.jsx
  src/components/Error/Error.styles.js
  src/components/Error/index.jsx
  src/components/RadioButton/index.jsx
  src/components/TestComponents.jsx
  src/main.jsx
  src/mocks/donations.js
  src/mocks/idols.js
  src/pages/DonationDetail/components/DonationDetailInfo.jsx
  src/pages/DonationDetail/components/DonationDetailSkeleton.jsx
  src/pages/DonationDetail/components/DonationDetailText.jsx
  src/pages/Landing/components/LandingFooter.jsx
  src/pages/List/Chart/index.jsx
  src/pages/List/Donation/Donation.styles.js
  src/pages/List/Donation/components/Card/Card.styles.js
  src/pages/List/Donation/components/Card/ProgressBar/ProgressBar.styles.js
  src/pages/List/Donation/components/Card/ProgressBar/index.jsx
  src/pages/List/Donation/components/Card/index.jsx
  src/pages/List/Donation/components/Carousel/Carousel.styles.js
  src/pages/List/Donation/components/Carousel/index.jsx
  src/pages/List/Donation/components/Skeleton/index.jsx
  src/pages/List/Donation/components/Skeleton/style/CardSkeleton.styles.js
  src/pages/List/Donation/components/Skeleton/style/Skeleton.styles.js
  src/pages/List/Donation/index.jsx
  src/pages/NotFound/NotFound.style.js
  src/pages/NotFound/NotFound.styles.js
  src/pages/NotFound/index.jsx
  src/pages/Testpage/index.jsx
Labels: 💄 디자인, 🔨 리팩토링, 🎨 UI 개선, 🚀 배포

#188 🐛 Fix: 차트 api 추가 및 차트 전환 문제 수정
  src/apis/chartApi.js
  src/hooks/useChart.js
  src/pages/List/Chart/components/hooks/useChart.jsx
  src/pages/List/Chart/index.jsx
Labels: 🐛 버그 수정

#186 ♻️ Fix: 랜딩 페이지 하단에서 리스트로 이동했을 때 페이지 하단으로 이동하는 이슈 해결
  src/App.jsx
  src/components/ScrollTop.jsx
Labels: 🎨 UI 개선

#189 v1.0.3
  src/App.jsx
  src/apis/chartApi.js
  src/components/ScrollTop.jsx
  src/hooks/useChart.js
  src/pages/List/Chart/components/hooks/useChart.jsx
  src/pages/List/Chart/index.jsx
Labels: ✨ 기능개발, 🐛 버그 수정, 🎨 UI 개선, 🚀 배포

#191 v1.0.4
  src/apis/charAPI.js
  src/pages/List/Chart/components/hooks/useChart.jsx
Labels: 🐛 버그 수정, 🚀 배포
